---
- name: Intro to T and F conditionals
  hosts: localhost
  gather_facts: no
  
  vars:
    bool_var: True
    msg_var: "TIME TO PANIC!"
  
  tasks:
    - name: Runs when bool_var is false
      when: bool_var|bool
      debug:
        msg: "{{ msg_var }}"
    
    - name: runs when bool_var is false
      when: not bool_var|bool
      debug:
        msg: "DON'T PANIC!"

