---
- name: Learning about line in file
  hosts: planetexpress:!farnsworth
  gather_facts: no
  
  vars:
    - fileloc: "/var/log/bootstrap.log"
  
  tasks:
    - name: Insert a line into {{ fileloc }}
      lineinfile:
        path: "{{ fileloc }}"
        regex: "^Setting up lib.*"
        line: "REDACTED by Ansible"
        backup: yes
      become: yes
