---
- name: Recalling vRS
  hosts: localhost
  ignore_errors: yes

  vars_files:
        - vars/fryvars.yml

  tasks:
          - name: Print the day of the week
            tags: one
            debug:
                    var: dayoftheweek

          - name: Print everything in ipv4
            tags: one
            debug:
                    var: prefix_list.ipv4

          - name: Print only ICM_TITAN and ICM_TITAN2
            debug:
                    var: item.name
            loop: "{{ prefix_list.ipv4 }}"
            
          - name: Print "10", "20", "30", "40"
            debug:
                    var: item.name.num
            loop: "{{ item.name.num }}" 

          - name: Print "act-10", "act-20" only
            debug:
                    var: item.name.num
            loop: "{{ item.name.num }}"
            when: item.name == "ICM_TITAN"

          - name: Print "rule-30", "rule-40" only
            debug:
                    var: item.name.num
            loop: "{{ item.name.num }}"
            when: item.name == "ICM_TITAN2"

