---
- name: Learning about get URL
  hosts: planetexpress:!farnsworth
  gather_facts: no
  
  tasks:
    - name: Create Directory
      file:
        path: ~/Downloads
        state: directory
    
    - name: Extract the tarball contents
      unarchive:
        src: http://www.clamav.net/downloads/production/clamav-0.99.3.tar.gz
        dest: "~/Downloads/{{ inventory_hostname }}.clamav-0.99.3.tar.gz"
        remote_src: yes
