---
- name: Learning about vars and var recall
  hosts: planetexpress

  vars:
          listofips:
                  - 192.168.1.0
                  - 10.0.0.1
                  - 172.0.0.8
          dlurl: "https://file-examples.com/wp-content/uploads/2017/10/file-sample_150kB.pdf"

  tasks:
          - name: Just print to the screen the value of lisofips
            debug:
                    var: listofips

          - name: Show a second way to print a list to the screen
            debug:
                    msg: "This is the listofips {{ listofips }}"

          - name: Download a critical PDF
            get_url:
                    url: "{{ dlurl }}"
                    dest: ~/
