---
- name: Lab - Install some stuff
  hosts: labhosts
  gather_facts: yes

  tasks:
    - name: module to guide install software apt
      apt:
        name: figlet
        update_cache: yes
        state: absent
      become: yes
