# Add to end of ~/.bashrc
if [ -f ~/.git-completion.bash ]; then
        source ~/.git-completion.bash
fi
if [ -f ~/.git-prompt.sh ]; then
        source ~/.git-prompt.sh
        export PS1='$(__git_ps1 "\[\033[01;35m\][git:%s]")\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;35m\]\w\[\033[00m\] \$ '
fi

